import json
import time
from typing import Dict, Any, List, Union

# Define the structured output type for a single file artifact
# This list structure is what the LLM is constrained to return.
FileArtifact = List[Dict[str, str]]

def fetch_web_content(url: str) -> str:
    """
    [SIMULATED TOOL] Fetches the main content from a given URL for specification ingestion.
    In a real ADK setup, this would use a dedicated web scraping library or tool.

    Args:
        url: The URL to scrape content from.

    Returns:
        The extracted text content of the webpage (simulated).
    """
    print(f"--- SIMULATING WEB SCRAPE of {url} ---")

    # Simple check for a mock path
    if "example.com/project-spec" in url:
        return (
            "Detailed Project Specification: Python Data Processor\n\n"
            "Goal: Create a two-file Python project. File 1 (main.py) must read a list of numbers from a string, "
            "and pass them to a function in File 2. File 2 (utility.py) must contain a function called 'calculate_average' "
            "that takes the list, computes the average, and returns it. The main file should then print the result. "
            "Input data: [10, 20, 30, 40, 50]. Project Name: Data Averager."
        )
    else:
        return f"Web content from {url} is not specific enough to act as a project specification. Please provide a more detailed URL or input."


def generate_project_artifacts(
    language: str,
    project_name: str,
    specification: str,
    output_format: str = "json"
) -> Dict[str, Union[str, FileArtifact]]:
    """
    Generates multiple project artifacts (code files and documentation) based on a detailed specification.

    Args:
        language: The primary programming language (e.g., "Python").
        project_name: The name of the project.
        specification: A detailed string (possibly from a scraped webpage) describing features.
        output_format: The desired output structure, typically "json".

    Returns:
        A dictionary containing the generated file artifacts and status.
    """

    # 1. Define the system instruction for the Code Generation LLM
    system_prompt = (
        "You are 'Winnie v0.2', an expert Multi-File Project Generation AI. Your task is to "
        "read the user's detailed specification and generate all requested project files. "
        "The files MUST be functional, written in Python, and well-commented. "
        "You MUST respond ONLY with a single JSON array that conforms to the required schema. "
        "Do not include any conversational text outside the JSON object. Ensure all strings are correctly escaped for JSON."
    )

    # 2. Define the user query/prompt
    user_query = (
        f"Generate the project named '{project_name}' in the '{language}' language. "
        f"The detailed specification is: ```{specification}```. "
        "The project MUST consist of at least three files: 'README.md', 'main.py', and 'utility.py'. "
        "Return the output as a JSON array of file objects, each containing 'filename' and 'content'."
    )

    # 3. Define the desired JSON structure (Schema) for multi-file output
    response_schema = {
        "type": "ARRAY",
        "items": {
            "type": "OBJECT",
            "properties": {
                "filename": {
                    "type": "STRING",
                    "description": "The file path and name, e.g., 'main.py' or 'README.md'."
                },
                "content": {
                    "type": "STRING",
                    "description": "The full, complete content of the file."
                }
            },
            "required": ["filename", "content"],
            "propertyOrdering": ["filename", "content"]
        }
    }

    # 4. Construct the API payload for Structured Generation (Mocked)
    # ... (API payload construction is omitted for this simulated tool)

    # --- SIMULATED RESPONSE BLOCK ---
    print("--- Calling Gemini API for Multi-File Generation (SIMULATED) ---")

    # We will simulate the output for the "Data Averager" based on the mock web content.
    if "Data Averager" in project_name or "calculate_average" in specification:
         simulated_files = [
            {
                "filename": "README.md",
                "content": (
                    f"# Project: {project_name}\n\n"
                    "This project was generated by Winnie v0.2. It demonstrates a multi-file Python "
                    "application designed to calculate the average of a list of numbers by delegating "
                    "the core logic to a separate utility file.\n\n"
                    "## Setup\n\nRequires Python 3.9+.\n\n## Usage\n\n```bash\npython main.py\n```"
                )
            },
            {
                "filename": "utility.py",
                "content": (
                    "\"\"\"Utility functions for calculating data statistics.\"\"\"\n\n"
                    "def calculate_average(data_list: list[int]) -> float:\n"
                    "    \"\"\"Calculates the average of a list of integers.\"\"\"\n"
                    "    if not data_list:\n"
                    "        return 0.0\n"
                    "    return sum(data_list) / len(data_list)\n"
                )
            },
            {
                "filename": "main.py",
                "content": (
                    "# Main runner script for the Data Averager project.\n"
                    "from utility import calculate_average\n\n"
                    "def main():\n"
                    "    # Input data as specified in the mock document\n"
                    "    numbers = [10, 20, 30, 40, 50]\n"
                    "    print(f\"Input numbers: {numbers}\")\n\n"
                    "    # Call function from the utility file\n"
                    "    average = calculate_average(numbers)\n\n"
                    "    print(f\"The calculated average is: {average}\")\n\n"
                    "if __name__ == '__main__':\n"
                    "    main()\n"
                )
            }
        ]
    else:
        simulated_files = [
            {
                "filename": "README.md",
                "content": f"# Project Documentation for {project_name}\n\nThis documentation was generated by Winnie v0.2 based on the specification: {specification}\n"
            },
            {
                "filename": "main.py",
                "content": f"# Main entry file for {project_name}\n# Code generation placeholder based on spec: {specification}"
            },
            {
                "filename": "utility.py",
                "content": "# Utility functions placeholder"
            }
        ]

    return {"files": simulated_files, "status": "success"}

    # --- END SIMULATED RESPONSE BLOCK ---

# Helper function to process the tool's output into a final, user-friendly response
def format_generation_response(result: Dict[str, Any]) -> str:
    """Formats the structured LLM output (an array of files) into a clean, markdown-friendly response."""
    if result.get("status") == "success":
        files = result.get("files", [])

        response_parts = [
            "## ✨ Winnie v0.2: Multi-File Project Generation Complete ✨\n\n",
            "I have successfully generated your project artifacts based on the specification. The following files are included in your project:\n"
        ]

        # Iterate through the array of file artifacts and format them
        for file in files:
            filename = file.get("filename", "unknown_file")
            content = file.get("content", "Content missing.")

            # Use appropriate language hint for code blocks
            language_hint = "python" if filename.endswith(".py") else "markdown"

            response_parts.append(f"\n### 📄 {filename}\n")

            if filename.endswith(".md"):
                # For documentation, display content directly as markdown
                response_parts.append(f"{content}\n")
            else:
                # For code, display inside a markdown code block
                response_parts.append(f"```{language_hint}\n{content}\n```\n")

        return "".join(response_parts)
    else:
        return f"Winnie v0.2 encountered an error during generation: {result.get('error_message', 'Unknown Error')}"
